FROM entando/entando-eap71-clustered-base:6.2.1
ENV APPBUILDERINTEGRATIONENABLED="true" \
    APPBUILDERBASEURL="/app-builder/"
COPY target/*.war /opt/eap/standalone/deployments/
RUN $ENTANDO_COMMON_PATH/init-derby-from-war.sh
