FROM entando/entando-tomcat-base:6.6.0


### Required OpenShift Labels
LABEL name="Entando App" \
      maintainer="dev@entando.com" \
      vendor="Entando Inc." \
      version="6.6" \
      release="6.6.0" \
      summary="Entando Application" \
      description="This Entando app engine application provides APIs and composition for Entando applications"

COPY target/generated-resources/licenses /licenses
COPY target/generated-resources/licenses.xml /

COPY --chown=185:0 target/*.war /usr/local/tomcat/webapps/

RUN $ENTANDO_COMMON_PATH/init-derby-from-war.sh

RUN rm -rf /tmp/*.jpg